name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install composer dependencies
      run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

    - name: Copy env.example file
      run: cp .env.example .env

    - name: Generate app key
      run: php artisan key:generate

    - name: Install npm packages using bun
      run: bun install

    - name: Build assets
      run: bun run build

    - name: Run PHPUnit tests
      run: ./vendor/bin/phpunit --colors=never
      env:
        DB_CONNECTION: sqlite
